import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";
import { Poppins } from 'next/font/google';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({ subsets: ['latin'],weight: ["100", "300", "400", "700", "900"], variable: '--font-poppins' });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className= 'antialiased font-poppins'

      >
        <main className="bg-white">
          <Navbar />
          <div className="flex flex-row w-full min-h-screen text-slate-900">
          {/* <Sidebar /> */}
            <div className="px-6 py-4 w-full bg-gradient-to-b from-violet-00/50 to-pink-200/60">
              {children}
            </div>
          </div>
          
        </main>
        
      </body>
    </html>
  );
}
